-- 2022년 1월의 도서 판매 데이터를 기준으로
-- 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여,
-- 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력
-- 결과는 저자 ID를 오름차순으로, 저자 ID가 같다면 카테고리를 내림차순 정렬해주세요.
WITH BOOK_INFO AS (
    SELECT BOOK_ID, CATEGORY, B.AUTHOR_ID, PRICE, AUTHOR_NAME
    FROM BOOK AS B
        INNER JOIN AUTHOR AS A
        ON B.AUTHOR_ID = A.AUTHOR_ID
)

SELECT I.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(I.PRICE * S.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS S
    INNER JOIN BOOK_INFO AS I
    ON S.BOOK_ID = I.BOOK_ID
WHERE S.SALES_DATE LIKE "%2022-01%"
GROUP BY I.AUTHOR_ID, CATEGORY
ORDER BY I.AUTHOR_ID, CATEGORY DESC;

